name: Build and Deploy to Azure

on:
  push:
    branches:
      - main  # or your branch name

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to ACR
      run: |
        az acr login --name sakshicicd

    - name: Build and Push Docker image
      run: |
        docker build -t sakshicicd.azurecr.io/node-todo-app:latest .
        docker push sakshicicd.azurecr.io/node-todo-app:latest

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set \
          --name todo-app \
          --resource-group CICDgroup \
          --container-image-name sakshicicd.azurecr.io/node-todo-app:latest \
          --container-registry-url https://sakshicicd.azurecr.io \
          --container-registry-username sakshicicd \
          --container-registry-password ${{ secrets.AZURE_CONTAINER_PASSWORD }}
